### ISSUE TITLE
v12 bundle does not include __POST_R3__ functions

### ISSUE THREAD

**Issue by midd17** [esm-bundle/angular__core#166]
I'm trying to make some of the @angular/* packages external. I use Angular v12 + Ivy, so it looks like I'm supposed to use  this bundle: 
https://unpkg.com/@esm-bundle/angular__core@12.0.0/system/es2015/ivy/angular-core.js

but I'm constantly getting "No provider for CompilerFactory!" errors.
When I looked at the core bundle I found that it uses PRE_R3 functions instead of POST_R3.

as for CompilerFactory:
`
let compileNgModuleFactory = compileNgModuleFactory__PRE_R3__;
`

It's interesting that on v11 the same core bundle uses POST_R3
`
var compileNgModuleFactory = compileNgModuleFactory__POST_R3__;
`

Shouldn't it always include POST_R3?

**Comment by arturovt** [comment]
There're newly a published version for Angular 13 which doesn't include `R3` functions. They were included in previous versions to switch between Ivy and View Engine, VE support has been removed.
