### ISSUE TITLE
esm bundle for Angular 10.2.5

### ISSUE THREAD

**Issue by donchilley** [esm-bundle/angular__core#250]
In reference to https://github.com/esm-bundle/angular__core , I'm attempting to get shared dependencies to work with single-spa, particularly to share one version of angular between my MFEs. My MFE's are built with Angular 10.2.5. my rxjs & rxjs/operators are esm bundled and it seems by angular needs to be esm as well. 

Could I get a esm bundled Angular@10.2.5 please?

**Comment by arturovt** [comment]
Unfortunately, we currently support only the latest version (which is 13). The VE support has been dropped thus the latest version is Ivy compatible only.
