### ISSUE TITLE
v11.0.0

### ISSUE THREAD

**Issue by Anelon** [esm-bundle/angular__core#47]
Can you add version 11.0.0 as a release?

**Comment by joeldenning** [comment]
I can add this in the next day or so.

**Comment by Anelon** [comment]
Is there any chance you can do it for the other angular bundles you have as well?

**Comment by joeldenning** [comment]
Done

https://cdn.jsdelivr.net/npm/@esm-bundle/angular__core@11.0.0/system/es2015/ivy/angular-core.js
https://cdn.jsdelivr.net/npm/@esm-bundle/angular__common@11.0.0/system/es2015/ivy/angular-common.js
https://cdn.jsdelivr.net/npm/@esm-bundle/angular__platform-browser@11.0.0/system/es2015/ivy/angular-platform-browser.js
https://cdn.jsdelivr.net/npm/@esm-bundle/angular__router@11.0.0/system/es2015/ivy/angular-router.js
